name: Update Dependencies

on:
  schedule:
    - cron: '0 0 * * 1'  # Weekly on Monday
  workflow_dispatch:

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x magnifier-app/gradlew
      
    - name: Update Gradle Wrapper
      run: cd magnifier-app && ./gradlew wrapper --gradle-version=latest
      
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'Update Gradle Wrapper to latest version'
        title: 'Update Gradle Wrapper'
        body: |
          This PR updates the Gradle Wrapper to the latest version.
          
          Auto-generated by GitHub Actions.
        branch: update-gradle-wrapper
        delete-branch: true